# Generated by Django 2.0 on 2020-05-30 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FApp', '0002_auto_20200530_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=50, null=True)),
                ('contact_group', models.CharField(blank=True, choices=[('PRE-SALES', 'PRE-SALES'), ('SALES', 'SALES'), ('SERVICE', 'SERVICE')], max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='profileinterest',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
        migrations.DeleteModel(
            name='ProfileInterest',
        ),
    ]
